name: Publish package to GitHub Packages

on:
  release:
    types: [created]
jobs:
  publish-package:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
